# Generated by Django 2.2.7 on 2021-12-01 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooking_forum', '0003_auto_20211201_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cooking_forum.Person'),
            preserve_default=False,
        ),
    ]
