# Generated by Django 2.2.7 on 2021-12-06 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooking_forum', '0004_user_person'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Recipe',
        ),
    ]
