# Generated by Django 2.2.7 on 2021-12-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking_forum', '0005_auto_20211206_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='recipes',
            new_name='ingredients',
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_name',
            field=models.TextField(blank=True),
        ),
    ]
